# Service name
service: serverless-nest-ddd

# Framework version constraint (semver constraint): '3', '^2.33'
frameworkVersion: '3'

plugins:
  - serverless-plugin-warmup
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs16.x
  region: 'eu-west-2'
  stage: ${opt:stage, "local"}
  memorySize: 256
  versionFunctions: false

functions:
  ExampleHandler:
    warmup:
      default:
        enabled: ${file(env.yml):environment.enabled}
    handler: src/infra/handlers/example-handler/index.exampleHandler
    events:
      - http:
          method: POST
          cors: true
          path: /example


custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'

  serverless-offline:
    lambdaPort: 3200
    httpPort: 4200

  warmup:
    default:
      memorySize: 256
      vpc: false
      events:
        - schedule: ${file(env.yml):environment.schedule}
      timeout: 20
      prewarm: true # Run WarmUp immediately after a deployment lambda
      payloadRaw: true # Won't JSON.stringify() the payload, may be necessary for Go/AppSync deployments
      concurrency: ${file(env.yml):environment.concurrency}

package:
  individually: true

